#aws
cloud.aws.sqs.enabled=true
cloud.aws.sqs.endpoint=http://localhost:4566
cloud.aws.sqs.to.wallet-transaction.queue-name=wallet-manager-portfolio-to-wallet-transaction
cloud.aws.sns.from.wallet-manager.portfolio.topic=wallet-manager-portfolio