#aws sqs
cloud.aws.sqs.enabled=true
cloud.aws.sqs.endpoint=http://localhost:4566
cloud.aws.sqs.to.wallet-transaction.queue-name=wallet-manager-portfolio-to-wallet-transaction

#aws sns
cloud.aws.sns.enabled=true
cloud.aws.sns.endpoint=http://localhost:4566
cloud.aws.sns.from.wallet-manager.portfolio.topic=wallet-manager-portfolio