spring.datasource.username=${}
spring.datasource.password=${}
spring.datasource.jdbc-url=${}
spring.datasource.pool-name=wallet-manager-hikari-pool
spring.datasource.driver-class-name=org.postgresql.Driver